### ISSUE TITLE
rdf distance units

### ISSUE THREAD

**Issue by tcmoore3** [mosdef-hub/msibi#2]
compute_current_rdf() calculates the rdf values correctly, but the distance is scaled by 1/10. i changed compute_current_rdf() to multiply r by 10 after the rdf calculation. this shouldn't effect any of the updating, since the update only uses the g(r) values. is there a better way to handle this?

**Comment by ctk3b** [comment]
To clearly define the problem for future reference:

MDTraj uses nanometers internally. Period. Any file format that typically uses any other unit in the biophysics community, e.g. .dcd, will be converted to nanometers upon reading such a file.

When running simulations in reduced units, e.g. HOOMD, the user would typically (or often) be developing potentials in those units. Thus it would make sense to specify their `r_cutoff`, `dr` and `pot_cutoff` in whatever those reduced units may be. This then causes a problem in the RDF calculation when specific file formats (but not others) are automatically converted to what MDTraj thinks is nanometers.

The simplest way to solve this problem would probably be to compile a list of all trajectory formats that do a conversion under the hood and do the appropriate reverse conversion on our end.

**Comment by tcmoore3** [comment]
Update: our plan moving forward is to assume we work in GROMACS units (nm, kJ/mol, ps).
