### ISSUE TITLE
Detect units of trajectory type

### ISSUE THREAD

**Issue by ctk3b** [mosdef-hub/msibi#21]
We shouldn't have to do [this](https://github.com/ctk3b/msibi/blob/master/msibi/pair.py#L99) and [this](https://github.com/ctk3b/msibi/blob/master/msibi/pair.py#L104) nor is it particularly safe since we're assuming it's a trajectory in angstroms.

It should be pretty straight forward to detect the type of trajectory and what units it uses.

**Comment by tcmoore3** [comment]
Yeah that's definitely not the best way to handle units. 

How would reduced units be handled? MDTraj does RDFs in nanometers. Does mdtraj work in nm internally, or does it work with in the units assumed from the trajectory? Can you get the units from a trajectory you load in mdtraj (that seems like it would be a useful mdtraj.Trajectory attribute if not already there). It seems like we need to add an attribute to msibi.MSIBI if you are working in reduced units (I also realize MSIBI maybe isn't the best class name in a packages named msibi).

**Comment by ctk3b** [comment]
1. Once loaded, mdtraj units are always assumed to be nanometers for any analysis purposes. However, the only way that this is "enforced" is by assuming the units of a a trajectory based on its extension. E.g., `.dcd` is assumed to be angstroms and will be converted to nanometers when loading.
2. I do not believe it's possible right now to see the units of the file of origin for an mdtraj trajectory object. I'll file an issue and see if they would be open to adding something that enables this.
  * The somewhat dirty workaround is for us to import all of the file classes and read the distance unit from there.
3. For things like reduced units, we also want to be able to specify on the msibi side, what the units of the trajectory are. This then needs to also take into account what mdtraj does by default when loading the thing. One option would be to add an optional flag to `mdtraj.load()` that overrides the file's distance units attribute.
4. We may have "over-object-oriented" this. In theory this could just be a single function, e.g. `msibi.optimize()`, which takes `states`, `pairs`, `n_iterations` and `engine` as before but also a list of `kwargs` which amount to kind of a "settings" list which we currently use to initialize `MSIBI`.
  * The syntax would then read something like:
    ```python
    settings = {rdf_cutoff: 3,
                n_rdf_points: 101, 
                pot_cutoff: None, 
                r_switch: None,
                smooth_rdfs: False,
                max_frames:1e3}

    msibi.optimize(states, pairs, n_iterations=10, engine=hoomd, *settings)
    ```

**Comment by tcmoore3** [comment]
> One option would be to add an optional flag to mdtraj.load() that overrides the file's distance units attribute.

I like this idea. Of course, we need to see if the mdtraj people would want to include this. It takes the ambiguity out of the units issue. 

I also like the idea of adding a `kwarg` argument to msibi.optimize. Not only would it make things a bit cleaner, but it could easily be extended to add different cutoffs for different pairs.

**Comment by ctk3b** [comment]
> we need to see if the mdtraj people would want to include this

Looking unlikely and I do agree that it detracts from the simplicity of using one set of units. 

Since we'll have to provide the units from the msibi side anyways, I think we should just go ahead and do the conversion on our end. We can curate a short list of the file formats that are not assumed to be in nanometers by MDTraj and provide an optional setting to do a distance unit conversion for working in reduced units which gets passed down to the [rdf calc](https://github.com/ctk3b/msibi/blob/master/msibi/pair.py#L86).

In general though, it might be a good philosophy to just start working in nanometers anyways and use the units typically used by a given file format, no? What convenience do you currently gain by working in reduced units? I would, perhaps naively, assume that since you're going back and forth between AA and CG systems anyways, it might make sense to do both with the same distance units.

**Comment by ctk3b** [comment]
Going to go with GROMACS/MDTraj/OpenMM units
