### ISSUE TITLE
checkpointing

### ISSUE THREAD

**Issue by tcmoore3** [mosdef-hub/msibi#3]
would be useful to make some sort of checkpointing available. this would be useful for running on clusters with a wall time limit. using the pickle module should work, i think?

**Comment by ctk3b** [comment]
I think it should in principal. Definitely worth trying but we'd have to
make sure that everything is truly stored within one MSIBI instance (which
I think is currently the case) and add some mechanism for restarting the
loop from wherever it was which could be a simple attribute that counts
iterations.

Also we should look into
https://github.com/dmtcp/dmtcp and if we can find any other packages that
are made for this.

**Comment by ctk3b** [comment]
Might be worth looking into: https://pypi.python.org/pypi/ediblepickle/1.0.2
