### ISSUE TITLE
Properly save g_r_all

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/msibi#33]
It looks like we're putting a lot of work into building `g_r_all` but only saving `g_r` (the last frame)

https://github.com/mosdef-hub/msibi/blob/master/msibi/pair.py#L137

**Comment by ctk3b** [comment]
I believe @tcmoore3 found this a few weeks ago - where dat PR?

**Comment by mattwthompson** [comment]
Coming from yours truly so it gets done

**Comment by mattwthompson** [comment]
#35
